Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -64,12 +64,7 @@ jobs:
         run: |
           dotnet test osu.sln --configuration Debug --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults --logger "trx;LogFileName=test_results.trx"
         continue-on-error: true
-
-      - name: Rename Cobertura file to coverage.sonarqube.xml
-        run: |
-          echo "Renaming Cobertura.xml to coverage.sonarqube.xml"
-          Rename-Item ./TestResults/Cobertura/Cobertura.xml ./TestResults/Cobertura/coverage.sonarqube.xml
-      
+        
       # Step 8: List files in the TestResults directory
       - name: List files in TestResults directory
         run: |
@@ -81,21 +76,32 @@ jobs:
         run: dotnet tool install --global dotnet-reportgenerator-globaltool
       
       # Step 10: Generate Cobertura format (with a fixed path)
+      # Generate Cobertura format
       - name: Generate Cobertura format
         run: |
           mkdir -p ./TestResults/Cobertura
-          reportgenerator "-reports:./TestResults/test_results.trx" "-targetdir:./TestResults/Cobertura" -reporttypes:Cobertura
-        continue-on-error: true
+          reportgenerator "-reports:./TestResults/test_results.trx" "
+                          "-targetdir:./TestResults/Cobertura" "
+                          -reporttypes:Cobertura "
+                          -reportfile:Cobertura.xml
       
-      # Step 11: Debug - Verify Cobertura directory
-      - name: Verify Cobertura directory and display contents
+      # Debug - Verify generated Cobertura report
+      - name: Debug - Verify Cobertura report
         run: |
-          echo "Listing files in Cobertura directory"
+          echo "Checking TestResults directory..."
+          dir ./TestResults
+          echo "Checking Cobertura directory..."
           dir ./TestResults/Cobertura
-          echo "Displaying Cobertura report content"
-          dir ./TestResults/Cobertura/coverage.sonarqube.xml
-        continue-on-error: true
-        
+      
+      # Rename the file if it exists
+      - name: Rename Cobertura.xml to coverage.sonarqube.xml
+        run: |
+          if (Test-Path ./TestResults/Cobertura/Cobertura.xml) {
+              Rename-Item ./TestResults/Cobertura/Cobertura.xml ./TestResults/Cobertura/coverage.sonarqube.xml
+          } else {
+              echo "Cobertura.xml file not found. Exiting rename step."
+              exit 1
+          }
       # Step 12: Display contents of Cobertura report
       - name: Display contents of Cobertura report
         run: |
